import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        height: '100%',
        backgroundColor: '#F0EBE8'
      },
    page:{
        flex: 1,
        backgroundColor: '#F0EBE8',
        height: '100%',
        overflow: 'scroll',
        
      },
    chooseText:{
      color: '#0D4D5E',
      fontFamily: 'DroidSans',
      fontStyle: 'normal',
      fontSize: '20pt',
      fontWeight: 700,
      lineHeight: '32px',
      textAlign: 'center',
    },
    popup: {
        filter: "drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))",
      },
    openDiv: {
      display: 'flex',
      width: "90%",
      minHeight: "20%",
      margin: "auto",
      alignItems: 'center',
    },
    doorDiv:{
      flex: 1,
      width: "90%",
      margin: "auto",
    },
    openDoor: {
      position: 'relative',
      filter: 'drop-shadow(0px 4px 4px #E1E0DE)',
      backgroundColor: '#FFFFFF',
      borderRadius: 30,
      width: "100%",
      paddingVertical: "60%",
      paddingHorizontal: "20%",
      alignItems: 'center',
      justifyContent: 'center',
      },
      openText: {
        color: '#0D4D5E', 
        // font: 'Droid Sans',
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '30px',
      },
      promptTitle:{
        color: '#0D4D5E',
        fontFamily: 'Hubballi',
        // fontStyle: 'normal',
        fontSize: 30,
        fontWeight: 700,
        paddingTop: 10,
      },
      prompt:{
        color: '#0D4D5E',
        fontFamily: 'Hubballi',
        fontStyle: 'normal',
        fontSize: 30,
        // lineHeight: '19px',
        paddingTop: 15,
      },
      interactive: {
        // Absolutely positioned to the `openDoor` container
        position: 'absolute',
        top:'60%',
        filter: 'drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))',
        backgroundColor: '#C5DA01',
        borderRadius: 20,
        paddingVertical: '1%',
        paddingHorizontal: '5%',
      },
      intText:{
        fontFamily: 'Inter',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '15pt',
        lineHeight: '24px',
        fontColor: '#0D4D5E',
      },
      compButton:{
        position: 'relative',
        width: "90%",
        height: "5%",
        margin: 'auto',
        backgroundColor: '#49A5AD',
        filter: 'drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))',
        borderRadius: 20,
        paddingVertical: '5%',
        justifyContent: 'center',
      },
      compText:{
        textAlign: 'center',
        color: '#FFFFFF',
        fontFamily: 'Inter',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '19pt',
        lineHeight: '30px',
        fontColor: '#FFFFFF',
      },

      helpButton:{
        position: 'relative',
        marginLeft: '45%',
        marginRight: '10%',
        marginBottom: '38pt',
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        filter: 'drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))',
      },
      exploreButton:{
        position: 'relative',
        borderRadius: 30,
        backgroundColor: '#0D4D5E',
        marginTop: '70%',
        // minHeight: '60%',
        minWidth: '22%',
        width: '30%',
        //Increase vertical height
        // height: '150px',

      },
      exploreText:{
        color: '#FFFFFF',
        fontFamily: 'DroidSans',
        paddingVertical: '5%',
        paddingHorizontal: '10%',
        textAlign: 'center',
        fontSize: '15pt',
      },
      doorActivityText:{
        fontFamily: 'DroidSans',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '20pt',
        lineHeight: '30px',
        color: '#0D4D5E',
        textAlign: 'center',
        marginTop: '37%',
      },
      helpText:{
        paddingVertical: '5%',
        textAlign: 'center',
        fontFamily: 'Hubballi',
        fontColor: '#0D4D5E',
        fontSize: '15pt',
        fontColor: '#49A5AD',
      },
      backArrow:{
        position: 'relative',
        right: '45%',
        bottom: '5%',
      },
      backText:{
        fontSize: '35px',
        fontWeight: 500,
        color: '#49A5AD',
      },
      alert:{
        margin: '10%',
        marginTop: '20%',
        maxW:"400",
        maxH:"800",
        height: '80%',
        borderRadius:30,
        backgroundColor:"#FFFFFF",
        filter:"drop-shadow(0px 4px 10px rgba(0, 0, 0, 0.25))",
      },
      backImage: {
          resizeMode: 'stretch',
          width: "100%",
          height: "100%",
      },

      backButton: {
          width: "25pt",
          height: "20pt",
          marginRight: "85%",
          marginTop: "15pt",
          marginBottom: "10%",
          position: "absolute",
      },
      doorIcon:{
        width: "28%", 
        height: 90,
        marginVertical: 20, 
        marginHorizontal: 10, 
        marginLeft: 10, 
        borderRadius: 20, 
        filter: 'drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))'
      },
      doorImage: {
        resizeMode: 'stretch',
        width: "100%",
        height: "100%",
      },
      
});

export {styles}